version: '3'

services:
  db:
    restart: always
    build: ./backend/db/
    restart: always
    environment:
      POSTGRES_PASSWORD: suppliera
      POSTGRES_USER: suppliera
    ports:
      - 5433:5432
  brands:
    restart: always
    build: ./backend/brands/
    volumes:
      - ./backend/brands:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm start
    links:
      - db
  categories:
    restart: always
    build: ./backend/categories/
    volumes:
      - ./backend/categories:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    command: npm start
  orders:
    restart: always
    build: ./backend/orders/
    volumes:
      - ./backend/orders:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3000
    command: npm start
  products:
    restart: always
    build: ./backend/products/
    volumes:
      - ./backend/products:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3000
    command: npm start
  users:
    restart: always
    build: ./backend/users/
    volumes:
      - ./backend/users:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3000
    command: npm start
  gateway:
    restart: on-failure:5
    build: ./backend/gateway/
    volumes:
      - ./backend/gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:3000
    command: npm start