--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2 (Ubuntu 12.2-2.pgdg16.04+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-2.pgdg16.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brands; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brands (
    "brandId" bigint NOT NULL,
    "brandName" character(24)
);


ALTER TABLE public.brands OWNER TO postgres;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    "categoryId" bigint NOT NULL,
    "categoryName" character(24)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    "orderId" bigint NOT NULL,
    "userId" bigint,
    "productId" bigint
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    "productId" bigint NOT NULL,
    "productImageSource" character varying(100),
    "productCode" character varying(10),
    "productName" character varying(100),
    "productDescription" character varying(200),
    "productStock" integer,
    "productPrice" bigint,
    "productBrand" bigint,
    "productCategory" bigint
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_productId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN "productId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_productId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    "userId" bigint NOT NULL,
    "userName" character(24),
    "userPassword" character varying(50),
    "userEmail" character varying(50),
    "userFirstName" character varying(24),
    "userLastName" character varying(24),
    "userAddress" character varying(50),
    "userPhone" character varying(50),
    "userGender" boolean,
    "userBirthDate" date
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: brands; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.brands ("brandId", "brandName") FROM stdin;
1	Nike                    
2	Adidas                  
3	Uniqlo                  
4	Hanes                   
5	Levi                    
6	Wrangler                
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories ("categoryId", "categoryName") FROM stdin;
1	Shoes                   
2	T-Shirts                
3	Pants                   
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders ("orderId", "userId", "productId") FROM stdin;
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product ("productId", "productImageSource", "productCode", "productName", "productDescription", "productStock", "productPrice", "productBrand", "productCategory") FROM stdin;
1	/images/wranglerPants	1	Cowboy Cut Slim Fit Jean	Wrangler® Cowboy Cut® jeans are a tried-and-true wardrobe staple for cowboys who demand a lot from their everyday clothes.	100	3900	6	3
2	/images/hanesTShirt	2	Hanes Men’s Everyday Short Sleeve Crewneck T-Shirt\n	Experience real comfort with this Hanes Everyday Tee. Made with 5.2-oz. super soft cotton.	100	1000	4	2
3	/images/nikeShoes	3	Nike Air VaporMax 360	Featuring a full-length foam midsole and VaporMax Air unit, the Nike Air VaporMax 360 gives you remarkable underfoot comfort with bold 2000s style inspired by the Air Max 360.\n\n	50	25000	1	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users ("userId", "userName", "userPassword", "userEmail", "userFirstName", "userLastName", "userAddress", "userPhone", "userGender", "userBirthDate") FROM stdin;
1	admin                   	admin	admin@suppliera.com	Adminko	Adminić	Adminska 7	12345678	t	2017-03-14
\.


--
-- Name: product_productId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."product_productId_seq"', 1, false);


--
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY ("brandId");


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY ("categoryId");


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY ("orderId");


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY ("productId");


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY ("userId");


--
-- Name: fki_brand_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_brand_fk ON public.product USING btree ("productBrand");


--
-- Name: fki_category_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_category_fk ON public.product USING btree ("productCategory");


--
-- Name: fki_product_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_product_fk ON public.orders USING btree ("productId");


--
-- Name: fki_user_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_user_fk ON public.orders USING btree ("userId");


--
-- Name: product brand_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT brand_fk FOREIGN KEY ("productBrand") REFERENCES public.brands("brandId") NOT VALID;


--
-- Name: product category_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT category_fk FOREIGN KEY ("productCategory") REFERENCES public.categories("categoryId") NOT VALID;


--
-- Name: orders product_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT product_fk FOREIGN KEY ("productId") REFERENCES public.product("productId") NOT VALID;


--
-- Name: orders user_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT user_fk FOREIGN KEY ("userId") REFERENCES public.users("userId") NOT VALID;


--
-- PostgreSQL database dump complete
--

